-- MySQL Script generated by MySQL Workbench
-- Fri Nov  8 11:23:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laboratorioTesting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboratorioTesting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorioTesting` DEFAULT CHARACTER SET utf8 ;
USE `laboratorioTesting` ;

-- -----------------------------------------------------
-- Table `laboratorioTesting`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `nro_telefono` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `rol` INT(3) NOT NULL,
  `dni` INT(8) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `user_id_UNIQUE` (`id_usuario` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `laboratorioTesting`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`materias` (
  `carrera` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cod_materia` INT NOT NULL,
  `materia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cod_materia`));


-- -----------------------------------------------------
-- Table `laboratorioTesting`.`proyectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`proyectores` (
  `id_key` INT NOT NULL AUTO_INCREMENT,
  `nro_inv` INT NOT NULL,
  `cod_rec` VARCHAR(255) NOT NULL,
  `estado` ENUM('Fun_D', 'Fun_ND', 'Rep', 'Baja_B', 'PATRON') NOT NULL DEFAULT 'FUN_D',
  `ubicacion` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `sn` VARCHAR(45) NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `horas_uso` VARCHAR(45) NULL,
  `detalles` VARCHAR(45) NULL,
  PRIMARY KEY (`id_key`),
  UNIQUE INDEX `id_key_UNIQUE` (`id_key` ASC) VISIBLE,
  UNIQUE INDEX `nro_inv_UNIQUE` (`nro_inv` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `laboratorioTesting`.`usuario_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`usuario_materia` (
  `usuarios_id_usuario` INT NOT NULL,
  `materias_cod_materia` INT NOT NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `materias_cod_materia`),
  INDEX `fk_usuario_materia_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_materia_materias1_idx` (`materias_cod_materia` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_materia_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `laboratorioTesting`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_materia_materias1`
    FOREIGN KEY (`materias_cod_materia`)
    REFERENCES `laboratorioTesting`.`materias` (`cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `laboratorioTesting`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NOT NULL,
  `proyectores_nro_inv` INT NOT NULL,
  `usuario_materia_usuarios_id_usuario` INT NOT NULL,
  `usuario_materia_materias_cod_materia` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `proyectores_nro_inv`, `usuario_materia_usuarios_id_usuario`, `usuario_materia_materias_cod_materia`),
  INDEX `fk_Reservas_proyectores1_idx` (`proyectores_nro_inv` ASC) VISIBLE,
  UNIQUE INDEX `id_reserva_UNIQUE` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_Reservas_usuario_materia1_idx` (`usuario_materia_usuarios_id_usuario` ASC, `usuario_materia_materias_cod_materia` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_proyectores1`
    FOREIGN KEY (`proyectores_nro_inv`)
    REFERENCES `laboratorioTesting`.`proyectores` (`nro_inv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_usuario_materia1`
    FOREIGN KEY (`usuario_materia_usuarios_id_usuario` , `usuario_materia_materias_cod_materia`)
    REFERENCES `laboratorioTesting`.`usuario_materia` (`usuarios_id_usuario` , `materias_cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `laboratorioTesting`.`retiros-devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorioTesting`.`retiros-devoluciones` (
  `reservas_id_reserva` INT NOT NULL,
  `f_retiro` DATETIME NOT NULL,
  `f_devolucion` DATETIME NULL,
  `aula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reservas_id_reserva`),
  INDEX `fk_retiros-devoluciones_reservas1_idx` (`reservas_id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_retiros-devoluciones_reservas1`
    FOREIGN KEY (`reservas_id_reserva`)
    REFERENCES `laboratorioTesting`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
